name: emboss
owner: brinkmanlab
description: EMBOSS tools
homepage_url: http://emboss.open-bio.org/
long_description: |
  The European Molecular Biology Open Software Suite (EMBOSS) is a high quality, well documented package of open source
  software tools for molecular biology. It includes over 200 applications for molecular sequence analysis and other
  common tasks in bioinformatics.
  Forked from https://github.com/galaxyproject/tools-iuc/tree/master/tools/emboss_5
remote_repository_url: https://github.com/brinkmanlab/galaxy-tools/tree/master/emboss
type: unrestricted
categories:
  - Sequence Analysis
  - Fasta Manipulation
