name: biopython-convert
owner: brinkmanlab
description: Interconvert between the various sequence file formats that BioPython supports
homepage_url: https://biopython.org/wiki/SeqIO
remote_repository_url: https://github.com/brinkmanlab/galaxy-tools/tree/master/biopython-convert
type: unrestricted
categories:
- Convert Formats
include:
- strip_components: 1
  source:
  - BioPython-Convert/test-data/has_plasmids.gbff
