name: mcl
owner: brinkmanlab
description: The Markov Cluster Algorithm, a cluster algorithm for graphs
homepage_url: https://micans.org/mcl/man/mcl.html
remote_repository_url: https://github.com/brinkmanlab/galaxy-tools/tree/master/mcl
type: unrestricted
