name: mash
owner: brinkmanlab
description: Fast genome and metagenome distance estimation using MinHash
homepage_url: https://mash.readthedocs.io/en/latest/
remote_repository_url: https://github.com/brinkmanlab/galaxy-tools/tree/master/<name of containing folder>
type: unrestricted
categories:
- Sequence Analysis
